// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ConnectionHistoryEntry {
  final BigInt atUnixMs;
  final String? peerNodeId;
  final String event;
  final String detail;
  final BigInt? establishMs;

  const ConnectionHistoryEntry({
    required this.atUnixMs,
    this.peerNodeId,
    required this.event,
    required this.detail,
    this.establishMs,
  });

  @override
  int get hashCode =>
      atUnixMs.hashCode ^
      peerNodeId.hashCode ^
      event.hashCode ^
      detail.hashCode ^
      establishMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionHistoryEntry &&
          runtimeType == other.runtimeType &&
          atUnixMs == other.atUnixMs &&
          peerNodeId == other.peerNodeId &&
          event == other.event &&
          detail == other.detail &&
          establishMs == other.establishMs;
}

class DiagnosticErrorEntry {
  final BigInt atUnixMs;
  final String message;

  const DiagnosticErrorEntry({required this.atUnixMs, required this.message});

  @override
  int get hashCode => atUnixMs.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticErrorEntry &&
          runtimeType == other.runtimeType &&
          atUnixMs == other.atUnixMs &&
          message == other.message;
}

class DiagnosticsSnapshot {
  final BigInt capturedAtUnixMs;
  final NodeIdentitySnapshot nodeIdentity;
  final List<PeerSnapshot> peers;
  final List<ConnectionHistoryEntry> connectionHistory;
  final List<DiagnosticErrorEntry> errorLog;
  final List<GossipTopicSnapshot> gossipTopics;

  const DiagnosticsSnapshot({
    required this.capturedAtUnixMs,
    required this.nodeIdentity,
    required this.peers,
    required this.connectionHistory,
    required this.errorLog,
    required this.gossipTopics,
  });

  @override
  int get hashCode =>
      capturedAtUnixMs.hashCode ^
      nodeIdentity.hashCode ^
      peers.hashCode ^
      connectionHistory.hashCode ^
      errorLog.hashCode ^
      gossipTopics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticsSnapshot &&
          runtimeType == other.runtimeType &&
          capturedAtUnixMs == other.capturedAtUnixMs &&
          nodeIdentity == other.nodeIdentity &&
          peers == other.peers &&
          connectionHistory == other.connectionHistory &&
          errorLog == other.errorLog &&
          gossipTopics == other.gossipTopics;
}

class GossipTopicSnapshot {
  final String topicId;
  final BigInt peerCount;

  const GossipTopicSnapshot({required this.topicId, required this.peerCount});

  @override
  int get hashCode => topicId.hashCode ^ peerCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GossipTopicSnapshot &&
          runtimeType == other.runtimeType &&
          topicId == other.topicId &&
          peerCount == other.peerCount;
}

class NodeIdentitySnapshot {
  final String nodeId;
  final String? relayUrl;
  final List<String> localListenAddrs;

  const NodeIdentitySnapshot({
    required this.nodeId,
    this.relayUrl,
    required this.localListenAddrs,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^ relayUrl.hashCode ^ localListenAddrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeIdentitySnapshot &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          relayUrl == other.relayUrl &&
          localListenAddrs == other.localListenAddrs;
}

enum PeerConnectionState { connected, known, disconnected }

enum PeerDiscoveryMethod { manual, relay, mdns, unknown }

class PeerSnapshot {
  final String nodeId;
  final PeerConnectionState state;
  final PeerDiscoveryMethod discoveredVia;
  final BigInt? lastSeenUnixMs;
  final int? rttMs;

  const PeerSnapshot({
    required this.nodeId,
    required this.state,
    required this.discoveredVia,
    this.lastSeenUnixMs,
    this.rttMs,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      state.hashCode ^
      discoveredVia.hashCode ^
      lastSeenUnixMs.hashCode ^
      rttMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerSnapshot &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          state == other.state &&
          discoveredVia == other.discoveredVia &&
          lastSeenUnixMs == other.lastSeenUnixMs &&
          rttMs == other.rttMs;
}
