// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A media file attached to a post, referenced by blob hash and fetched
/// on demand from the author (or any peer that holds it).
class MediaAttachment {
  final MediaKind kind;
  final String blobHash;
  final int byteLen;
  final String mime;

  /// Duration for audio/video, so cards can render it before the blob arrives.
  final int? durationMs;

  /// Peak buckets for audio waveforms, rendered before the blob arrives.
  final Uint8List? waveform;
  final int? width;
  final int? height;

  /// Original file name, used by the external-open fallback card.
  final String? fileName;

  /// Per-blob AEAD key + nonce (32 + 12 bytes) when the blob replicates as
  /// ciphertext. Only ever present inside encrypted post payloads, so the
  /// key is protected by the group encryption around it. `None` = plaintext
  /// blob (public posts).
  final Uint8List? blobSecret;

  const MediaAttachment({
    required this.kind,
    required this.blobHash,
    required this.byteLen,
    required this.mime,
    this.durationMs,
    this.waveform,
    this.width,
    this.height,
    this.fileName,
    this.blobSecret,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      blobHash.hashCode ^
      byteLen.hashCode ^
      mime.hashCode ^
      durationMs.hashCode ^
      waveform.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fileName.hashCode ^
      blobSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaAttachment &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          blobHash == other.blobHash &&
          byteLen == other.byteLen &&
          mime == other.mime &&
          durationMs == other.durationMs &&
          waveform == other.waveform &&
          width == other.width &&
          height == other.height &&
          fileName == other.fileName &&
          blobSecret == other.blobSecret;
}

enum MediaKind { photo, audio, video, file }

/// A friendship request awaiting the profile owner's answer.
class PendingFriendRequest {
  final String requesterProfileId;
  final String requesterDisplayName;
  final String? greeting;
  final int recordedAt;

  const PendingFriendRequest({
    required this.requesterProfileId,
    required this.requesterDisplayName,
    this.greeting,
    required this.recordedAt,
  });

  @override
  int get hashCode =>
      requesterProfileId.hashCode ^
      requesterDisplayName.hashCode ^
      greeting.hashCode ^
      recordedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingFriendRequest &&
          runtimeType == other.runtimeType &&
          requesterProfileId == other.requesterProfileId &&
          requesterDisplayName == other.requesterDisplayName &&
          greeting == other.greeting &&
          recordedAt == other.recordedAt;
}

/// A post as reconstructed from a profile's operation history.
class ReducedPost {
  final String profileId;
  final String postId;
  final String body;
  final List<MediaAttachment> media;
  final Visibility visibility;
  final int? expiresAt;
  final int createdAt;
  final bool edited;

  const ReducedPost({
    required this.profileId,
    required this.postId,
    required this.body,
    required this.media,
    required this.visibility,
    this.expiresAt,
    required this.createdAt,
    required this.edited,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      postId.hashCode ^
      body.hashCode ^
      media.hashCode ^
      visibility.hashCode ^
      expiresAt.hashCode ^
      createdAt.hashCode ^
      edited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReducedPost &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          postId == other.postId &&
          body == other.body &&
          media == other.media &&
          visibility == other.visibility &&
          expiresAt == other.expiresAt &&
          createdAt == other.createdAt &&
          edited == other.edited;
}

/// Reach of a post, chosen by its author.
///
/// In v1 replication is pure friend-circle: `Public` and `Circles` are stored
/// for forward compatibility but replicate exactly like `Friends`. `Private`
/// posts are structurally local-only — they must never be encoded into a
/// [`DomainOperation`] (see `PrivatePostsStore`).
enum Visibility { public, circles, friends, private }
