// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/commands.dart';
import 'api/lifecycle.dart';
import 'api/media.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'diagnostics.dart';
import 'domain.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'profile.dart';
import 'runtime.dart';
import 'settings.dart';
import 'state.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiLifecycleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1796930313;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'jyn',
        ioDirectory: '../core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCommandsDeletePost({required String postId});

  Future<void> crateApiCommandsEditPost({
    required String postId,
    required String body,
  });

  Stream<JynEvent> crateApiLifecycleEvents();

  Future<SettingsView> crateApiSettingsGetSettings();

  Future<void> crateApiLifecycleInitApp();

  Future<void> crateApiCommandsKeepPost({
    required String postAuthorProfileId,
    required String postId,
  });

  Future<String?> crateApiMediaLocalMediaPath({required String blobHash});

  Future<String> crateApiLifecycleMyFriendCode();

  Future<String> crateApiLifecycleNodeDataDir();

  Future<void> crateApiCommandsPublishComment({
    required String postAuthorProfileId,
    required String postId,
    required String body,
  });

  Future<void> crateApiCommandsPublishPost({
    required String body,
    required Visibility visibility,
    BigInt? lifetimeSecs,
    required List<MediaDraftInput> media,
  });

  Future<void> crateApiCommandsReleaseKeep({
    required String postAuthorProfileId,
    required String postId,
  });

  Future<void> crateApiCommandsRemoveFriend({required String profileId});

  Future<void> crateApiCommandsRequestFriendship({
    required String friendCode,
    String? greeting,
  });

  Future<void> crateApiCommandsRequestFriendshipById({
    required String profileId,
    String? greeting,
  });

  Future<void> crateApiMediaRequestMedia({required String blobHash});

  Future<void> crateApiCommandsRespondFriendship({
    required String requesterProfileId,
    required bool accept,
  });

  Future<void> crateApiLifecycleSetAppFocused({required bool focused});

  Future<void> crateApiCommandsSetHeart({
    required String postAuthorProfileId,
    required String postId,
    required bool active,
  });

  Future<bool> crateApiSettingsSetMdnsEnabled({required bool enabled});

  Future<void> crateApiCommandsSetPostLifetime({
    required String postId,
    BigInt? expiresAt,
  });

  Future<bool> crateApiSettingsSetRelayConfig({
    required RelayMode relayMode,
    String? customRelayUrl,
  });

  Future<void> crateApiLifecycleStartNode({String? dataDirOverride});

  Future<void> crateApiCommandsUpdateProfile({
    required String displayName,
    required String bio,
    required Visibility defaultVisibility,
    BigInt? defaultLifetimeSecs,
    required bool markOnboarded,
  });

  Future<WavSummary> crateApiMediaVoiceNoteSummary({required String wavPath});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCommandsDeletePost({required String postId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsDeletePostConstMeta,
        argValues: [postId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsDeletePostConstMeta =>
      const TaskConstMeta(debugName: "delete_post", argNames: ["postId"]);

  @override
  Future<void> crateApiCommandsEditPost({
    required String postId,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postId, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsEditPostConstMeta,
        argValues: [postId, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsEditPostConstMeta =>
      const TaskConstMeta(debugName: "edit_post", argNames: ["postId", "body"]);

  @override
  Stream<JynEvent> crateApiLifecycleEvents() {
    final sink = RustStreamSink<JynEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_jyn_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiLifecycleEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLifecycleEventsConstMeta =>
      const TaskConstMeta(debugName: "events", argNames: ["sink"]);

  @override
  Future<SettingsView> crateApiSettingsGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<void> crateApiLifecycleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLifecycleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiCommandsKeepPost({
    required String postAuthorProfileId,
    required String postId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postAuthorProfileId, serializer);
          sse_encode_String(postId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsKeepPostConstMeta,
        argValues: [postAuthorProfileId, postId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsKeepPostConstMeta => const TaskConstMeta(
    debugName: "keep_post",
    argNames: ["postAuthorProfileId", "postId"],
  );

  @override
  Future<String?> crateApiMediaLocalMediaPath({required String blobHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(blobHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaLocalMediaPathConstMeta,
        argValues: [blobHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaLocalMediaPathConstMeta =>
      const TaskConstMeta(
        debugName: "local_media_path",
        argNames: ["blobHash"],
      );

  @override
  Future<String> crateApiLifecycleMyFriendCode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLifecycleMyFriendCodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleMyFriendCodeConstMeta =>
      const TaskConstMeta(debugName: "my_friend_code", argNames: []);

  @override
  Future<String> crateApiLifecycleNodeDataDir() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLifecycleNodeDataDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleNodeDataDirConstMeta =>
      const TaskConstMeta(debugName: "node_data_dir", argNames: []);

  @override
  Future<void> crateApiCommandsPublishComment({
    required String postAuthorProfileId,
    required String postId,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postAuthorProfileId, serializer);
          sse_encode_String(postId, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsPublishCommentConstMeta,
        argValues: [postAuthorProfileId, postId, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsPublishCommentConstMeta =>
      const TaskConstMeta(
        debugName: "publish_comment",
        argNames: ["postAuthorProfileId", "postId", "body"],
      );

  @override
  Future<void> crateApiCommandsPublishPost({
    required String body,
    required Visibility visibility,
    BigInt? lifetimeSecs,
    required List<MediaDraftInput> media,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(body, serializer);
          sse_encode_visibility(visibility, serializer);
          sse_encode_opt_box_autoadd_u_64(lifetimeSecs, serializer);
          sse_encode_list_media_draft_input(media, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsPublishPostConstMeta,
        argValues: [body, visibility, lifetimeSecs, media],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsPublishPostConstMeta =>
      const TaskConstMeta(
        debugName: "publish_post",
        argNames: ["body", "visibility", "lifetimeSecs", "media"],
      );

  @override
  Future<void> crateApiCommandsReleaseKeep({
    required String postAuthorProfileId,
    required String postId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postAuthorProfileId, serializer);
          sse_encode_String(postId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsReleaseKeepConstMeta,
        argValues: [postAuthorProfileId, postId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsReleaseKeepConstMeta =>
      const TaskConstMeta(
        debugName: "release_keep",
        argNames: ["postAuthorProfileId", "postId"],
      );

  @override
  Future<void> crateApiCommandsRemoveFriend({required String profileId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsRemoveFriendConstMeta,
        argValues: [profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsRemoveFriendConstMeta =>
      const TaskConstMeta(debugName: "remove_friend", argNames: ["profileId"]);

  @override
  Future<void> crateApiCommandsRequestFriendship({
    required String friendCode,
    String? greeting,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(friendCode, serializer);
          sse_encode_opt_String(greeting, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsRequestFriendshipConstMeta,
        argValues: [friendCode, greeting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsRequestFriendshipConstMeta =>
      const TaskConstMeta(
        debugName: "request_friendship",
        argNames: ["friendCode", "greeting"],
      );

  @override
  Future<void> crateApiCommandsRequestFriendshipById({
    required String profileId,
    String? greeting,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_opt_String(greeting, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsRequestFriendshipByIdConstMeta,
        argValues: [profileId, greeting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsRequestFriendshipByIdConstMeta =>
      const TaskConstMeta(
        debugName: "request_friendship_by_id",
        argNames: ["profileId", "greeting"],
      );

  @override
  Future<void> crateApiMediaRequestMedia({required String blobHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(blobHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaRequestMediaConstMeta,
        argValues: [blobHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRequestMediaConstMeta =>
      const TaskConstMeta(debugName: "request_media", argNames: ["blobHash"]);

  @override
  Future<void> crateApiCommandsRespondFriendship({
    required String requesterProfileId,
    required bool accept,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(requesterProfileId, serializer);
          sse_encode_bool(accept, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsRespondFriendshipConstMeta,
        argValues: [requesterProfileId, accept],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsRespondFriendshipConstMeta =>
      const TaskConstMeta(
        debugName: "respond_friendship",
        argNames: ["requesterProfileId", "accept"],
      );

  @override
  Future<void> crateApiLifecycleSetAppFocused({required bool focused}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(focused, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLifecycleSetAppFocusedConstMeta,
        argValues: [focused],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleSetAppFocusedConstMeta =>
      const TaskConstMeta(debugName: "set_app_focused", argNames: ["focused"]);

  @override
  Future<void> crateApiCommandsSetHeart({
    required String postAuthorProfileId,
    required String postId,
    required bool active,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postAuthorProfileId, serializer);
          sse_encode_String(postId, serializer);
          sse_encode_bool(active, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsSetHeartConstMeta,
        argValues: [postAuthorProfileId, postId, active],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsSetHeartConstMeta => const TaskConstMeta(
    debugName: "set_heart",
    argNames: ["postAuthorProfileId", "postId", "active"],
  );

  @override
  Future<bool> crateApiSettingsSetMdnsEnabled({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsSetMdnsEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSetMdnsEnabledConstMeta =>
      const TaskConstMeta(debugName: "set_mdns_enabled", argNames: ["enabled"]);

  @override
  Future<void> crateApiCommandsSetPostLifetime({
    required String postId,
    BigInt? expiresAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(postId, serializer);
          sse_encode_opt_box_autoadd_u_64(expiresAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsSetPostLifetimeConstMeta,
        argValues: [postId, expiresAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsSetPostLifetimeConstMeta =>
      const TaskConstMeta(
        debugName: "set_post_lifetime",
        argNames: ["postId", "expiresAt"],
      );

  @override
  Future<bool> crateApiSettingsSetRelayConfig({
    required RelayMode relayMode,
    String? customRelayUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_relay_mode(relayMode, serializer);
          sse_encode_opt_String(customRelayUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSettingsSetRelayConfigConstMeta,
        argValues: [relayMode, customRelayUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSetRelayConfigConstMeta =>
      const TaskConstMeta(
        debugName: "set_relay_config",
        argNames: ["relayMode", "customRelayUrl"],
      );

  @override
  Future<void> crateApiLifecycleStartNode({String? dataDirOverride}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(dataDirOverride, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLifecycleStartNodeConstMeta,
        argValues: [dataDirOverride],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleStartNodeConstMeta => const TaskConstMeta(
    debugName: "start_node",
    argNames: ["dataDirOverride"],
  );

  @override
  Future<void> crateApiCommandsUpdateProfile({
    required String displayName,
    required String bio,
    required Visibility defaultVisibility,
    BigInt? defaultLifetimeSecs,
    required bool markOnboarded,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(displayName, serializer);
          sse_encode_String(bio, serializer);
          sse_encode_visibility(defaultVisibility, serializer);
          sse_encode_opt_box_autoadd_u_64(defaultLifetimeSecs, serializer);
          sse_encode_bool(markOnboarded, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCommandsUpdateProfileConstMeta,
        argValues: [
          displayName,
          bio,
          defaultVisibility,
          defaultLifetimeSecs,
          markOnboarded,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommandsUpdateProfileConstMeta =>
      const TaskConstMeta(
        debugName: "update_profile",
        argNames: [
          "displayName",
          "bio",
          "defaultVisibility",
          "defaultLifetimeSecs",
          "markOnboarded",
        ],
      );

  @override
  Future<WavSummary> crateApiMediaVoiceNoteSummary({required String wavPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wavPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wav_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaVoiceNoteSummaryConstMeta,
        argValues: [wavPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaVoiceNoteSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "voice_note_summary",
        argNames: ["wavPath"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<JynEvent> dco_decode_StreamSink_jyn_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiagnosticsSnapshot dco_decode_box_autoadd_diagnostics_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_diagnostics_snapshot(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  UserProfile dco_decode_box_autoadd_user_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_user_profile(raw);
  }

  @protected
  ConnectionHistoryEntry dco_decode_connection_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConnectionHistoryEntry(
      atUnixMs: dco_decode_u_64(arr[0]),
      peerNodeId: dco_decode_opt_String(arr[1]),
      event: dco_decode_String(arr[2]),
      detail: dco_decode_String(arr[3]),
      establishMs: dco_decode_opt_box_autoadd_u_64(arr[4]),
    );
  }

  @protected
  DiagnosticErrorEntry dco_decode_diagnostic_error_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiagnosticErrorEntry(
      atUnixMs: dco_decode_u_64(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  DiagnosticsSnapshot dco_decode_diagnostics_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DiagnosticsSnapshot(
      capturedAtUnixMs: dco_decode_u_64(arr[0]),
      nodeIdentity: dco_decode_node_identity_snapshot(arr[1]),
      peers: dco_decode_list_peer_snapshot(arr[2]),
      connectionHistory: dco_decode_list_connection_history_entry(arr[3]),
      errorLog: dco_decode_list_diagnostic_error_entry(arr[4]),
      gossipTopics: dco_decode_list_gossip_topic_snapshot(arr[5]),
    );
  }

  @protected
  FriendEntry dco_decode_friend_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FriendEntry(
      profileId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      followsMeBack: dco_decode_bool(arr[2]),
    );
  }

  @protected
  GhostCard dco_decode_ghost_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GhostCard(
      carrierDisplayName: dco_decode_String(arr[0]),
      authorProfileId: dco_decode_String(arr[1]),
    );
  }

  @protected
  GossipTopicSnapshot dco_decode_gossip_topic_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GossipTopicSnapshot(
      topicId: dco_decode_String(arr[0]),
      peerCount: dco_decode_usize(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  JynEvent dco_decode_jyn_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return JynEvent_River(
          posts: dco_decode_list_river_post(raw[1]),
          ghosts: dco_decode_list_ghost_card(raw[2]),
        );
      case 1:
        return JynEvent_Profile(
          profile: dco_decode_box_autoadd_user_profile(raw[1]),
        );
      case 2:
        return JynEvent_Friends(
          friends: dco_decode_list_friend_entry(raw[1]),
          pending: dco_decode_list_pending_friend_request(raw[2]),
        );
      case 3:
        return JynEvent_Diagnostics(
          snapshot: dco_decode_box_autoadd_diagnostics_snapshot(raw[1]),
        );
      case 4:
        return JynEvent_MediaReady(
          blobHash: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
        );
      case 5:
        return JynEvent_MediaFailed(
          blobHash: dco_decode_String(raw[1]),
          errorMessage: dco_decode_String(raw[2]),
        );
      case 6:
        return JynEvent_Error(
          context: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConnectionHistoryEntry> dco_decode_list_connection_history_entry(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_connection_history_entry)
        .toList();
  }

  @protected
  List<DiagnosticErrorEntry> dco_decode_list_diagnostic_error_entry(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_diagnostic_error_entry)
        .toList();
  }

  @protected
  List<FriendEntry> dco_decode_list_friend_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_friend_entry).toList();
  }

  @protected
  List<GhostCard> dco_decode_list_ghost_card(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ghost_card).toList();
  }

  @protected
  List<GossipTopicSnapshot> dco_decode_list_gossip_topic_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_gossip_topic_snapshot)
        .toList();
  }

  @protected
  List<MediaAttachment> dco_decode_list_media_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_attachment).toList();
  }

  @protected
  List<MediaDraftInput> dco_decode_list_media_draft_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_draft_input).toList();
  }

  @protected
  List<PeerSnapshot> dco_decode_list_peer_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_snapshot).toList();
  }

  @protected
  List<PendingFriendRequest> dco_decode_list_pending_friend_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_pending_friend_request)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RiverComment> dco_decode_list_river_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_river_comment).toList();
  }

  @protected
  List<RiverHeart> dco_decode_list_river_heart(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_river_heart).toList();
  }

  @protected
  List<RiverPost> dco_decode_list_river_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_river_post).toList();
  }

  @protected
  MediaAttachment dco_decode_media_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MediaAttachment(
      kind: dco_decode_media_kind(arr[0]),
      blobHash: dco_decode_String(arr[1]),
      byteLen: dco_decode_u_64(arr[2]),
      mime: dco_decode_String(arr[3]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[4]),
      waveform: dco_decode_opt_list_prim_u_8_strict(arr[5]),
      width: dco_decode_opt_box_autoadd_u_32(arr[6]),
      height: dco_decode_opt_box_autoadd_u_32(arr[7]),
      fileName: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  MediaDraftInput dco_decode_media_draft_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MediaDraftInput(
      path: dco_decode_String(arr[0]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[1]),
      waveform: dco_decode_opt_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  MediaKind dco_decode_media_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaKind.values[raw as int];
  }

  @protected
  NodeIdentitySnapshot dco_decode_node_identity_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NodeIdentitySnapshot(
      nodeId: dco_decode_String(arr[0]),
      relayUrl: dco_decode_opt_String(arr[1]),
      localListenAddrs: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PeerConnectionState dco_decode_peer_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerConnectionState.values[raw as int];
  }

  @protected
  PeerDiscoveryMethod dco_decode_peer_discovery_method(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerDiscoveryMethod.values[raw as int];
  }

  @protected
  PeerSnapshot dco_decode_peer_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PeerSnapshot(
      nodeId: dco_decode_String(arr[0]),
      state: dco_decode_peer_connection_state(arr[1]),
      discoveredVia: dco_decode_peer_discovery_method(arr[2]),
      lastSeenUnixMs: dco_decode_opt_box_autoadd_u_64(arr[3]),
      rttMs: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  PendingFriendRequest dco_decode_pending_friend_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PendingFriendRequest(
      requesterProfileId: dco_decode_String(arr[0]),
      requesterDisplayName: dco_decode_String(arr[1]),
      greeting: dco_decode_opt_String(arr[2]),
      recordedAt: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  ReducedPost dco_decode_reduced_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ReducedPost(
      profileId: dco_decode_String(arr[0]),
      postId: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      media: dco_decode_list_media_attachment(arr[3]),
      visibility: dco_decode_visibility(arr[4]),
      expiresAt: dco_decode_opt_box_autoadd_u_64(arr[5]),
      createdAt: dco_decode_u_64(arr[6]),
      edited: dco_decode_bool(arr[7]),
    );
  }

  @protected
  RelayMode dco_decode_relay_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RelayMode.values[raw as int];
  }

  @protected
  RiverComment dco_decode_river_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RiverComment(
      commenterProfileId: dco_decode_String(arr[0]),
      commenterDisplayName: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      createdAt: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  RiverHeart dco_decode_river_heart(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RiverHeart(
      hearterProfileId: dco_decode_String(arr[0]),
      hearterDisplayName: dco_decode_String(arr[1]),
    );
  }

  @protected
  RiverPost dco_decode_river_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RiverPost(
      authorProfileId: dco_decode_String(arr[0]),
      authorDisplayName: dco_decode_String(arr[1]),
      isSelf: dco_decode_bool(arr[2]),
      post: dco_decode_reduced_post(arr[3]),
      hearts: dco_decode_list_river_heart(arr[4]),
      heartedByMe: dco_decode_bool(arr[5]),
      comments: dco_decode_list_river_comment(arr[6]),
      keptByMe: dco_decode_bool(arr[7]),
    );
  }

  @protected
  SettingsView dco_decode_settings_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SettingsView(
      mdnsEnabled: dco_decode_bool(arr[0]),
      relayMode: dco_decode_relay_mode(arr[1]),
      customRelayUrl: dco_decode_opt_String(arr[2]),
      defaultDownloadDir: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserProfile dco_decode_user_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return UserProfile(
      version: dco_decode_u_8(arr[0]),
      profileId: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      bio: dco_decode_String(arr[3]),
      defaultVisibility: dco_decode_visibility(arr[4]),
      defaultLifetimeSecs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      onboarded: dco_decode_bool(arr[6]),
      createdAt: dco_decode_u_64(arr[7]),
      updatedAt: dco_decode_u_64(arr[8]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Visibility dco_decode_visibility(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Visibility.values[raw as int];
  }

  @protected
  WavSummary dco_decode_wav_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WavSummary(
      durationMs: dco_decode_u_64(arr[0]),
      waveform: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<JynEvent> sse_decode_StreamSink_jyn_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiagnosticsSnapshot sse_decode_box_autoadd_diagnostics_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_diagnostics_snapshot(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  UserProfile sse_decode_box_autoadd_user_profile(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_user_profile(deserializer));
  }

  @protected
  ConnectionHistoryEntry sse_decode_connection_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_atUnixMs = sse_decode_u_64(deserializer);
    var var_peerNodeId = sse_decode_opt_String(deserializer);
    var var_event = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_establishMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return ConnectionHistoryEntry(
      atUnixMs: var_atUnixMs,
      peerNodeId: var_peerNodeId,
      event: var_event,
      detail: var_detail,
      establishMs: var_establishMs,
    );
  }

  @protected
  DiagnosticErrorEntry sse_decode_diagnostic_error_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_atUnixMs = sse_decode_u_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    return DiagnosticErrorEntry(atUnixMs: var_atUnixMs, message: var_message);
  }

  @protected
  DiagnosticsSnapshot sse_decode_diagnostics_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_capturedAtUnixMs = sse_decode_u_64(deserializer);
    var var_nodeIdentity = sse_decode_node_identity_snapshot(deserializer);
    var var_peers = sse_decode_list_peer_snapshot(deserializer);
    var var_connectionHistory = sse_decode_list_connection_history_entry(
      deserializer,
    );
    var var_errorLog = sse_decode_list_diagnostic_error_entry(deserializer);
    var var_gossipTopics = sse_decode_list_gossip_topic_snapshot(deserializer);
    return DiagnosticsSnapshot(
      capturedAtUnixMs: var_capturedAtUnixMs,
      nodeIdentity: var_nodeIdentity,
      peers: var_peers,
      connectionHistory: var_connectionHistory,
      errorLog: var_errorLog,
      gossipTopics: var_gossipTopics,
    );
  }

  @protected
  FriendEntry sse_decode_friend_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_profileId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_followsMeBack = sse_decode_bool(deserializer);
    return FriendEntry(
      profileId: var_profileId,
      displayName: var_displayName,
      followsMeBack: var_followsMeBack,
    );
  }

  @protected
  GhostCard sse_decode_ghost_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_carrierDisplayName = sse_decode_String(deserializer);
    var var_authorProfileId = sse_decode_String(deserializer);
    return GhostCard(
      carrierDisplayName: var_carrierDisplayName,
      authorProfileId: var_authorProfileId,
    );
  }

  @protected
  GossipTopicSnapshot sse_decode_gossip_topic_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_topicId = sse_decode_String(deserializer);
    var var_peerCount = sse_decode_usize(deserializer);
    return GossipTopicSnapshot(topicId: var_topicId, peerCount: var_peerCount);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  JynEvent sse_decode_jyn_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_posts = sse_decode_list_river_post(deserializer);
        var var_ghosts = sse_decode_list_ghost_card(deserializer);
        return JynEvent_River(posts: var_posts, ghosts: var_ghosts);
      case 1:
        var var_profile = sse_decode_box_autoadd_user_profile(deserializer);
        return JynEvent_Profile(profile: var_profile);
      case 2:
        var var_friends = sse_decode_list_friend_entry(deserializer);
        var var_pending = sse_decode_list_pending_friend_request(deserializer);
        return JynEvent_Friends(friends: var_friends, pending: var_pending);
      case 3:
        var var_snapshot = sse_decode_box_autoadd_diagnostics_snapshot(
          deserializer,
        );
        return JynEvent_Diagnostics(snapshot: var_snapshot);
      case 4:
        var var_blobHash = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return JynEvent_MediaReady(blobHash: var_blobHash, path: var_path);
      case 5:
        var var_blobHash = sse_decode_String(deserializer);
        var var_errorMessage = sse_decode_String(deserializer);
        return JynEvent_MediaFailed(
          blobHash: var_blobHash,
          errorMessage: var_errorMessage,
        );
      case 6:
        var var_context = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return JynEvent_Error(context: var_context, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConnectionHistoryEntry> sse_decode_list_connection_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConnectionHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connection_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiagnosticErrorEntry> sse_decode_list_diagnostic_error_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiagnosticErrorEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diagnostic_error_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<FriendEntry> sse_decode_list_friend_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FriendEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_friend_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<GhostCard> sse_decode_list_ghost_card(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GhostCard>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ghost_card(deserializer));
    }
    return ans_;
  }

  @protected
  List<GossipTopicSnapshot> sse_decode_list_gossip_topic_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GossipTopicSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gossip_topic_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaAttachment> sse_decode_list_media_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaAttachment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaDraftInput> sse_decode_list_media_draft_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaDraftInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_draft_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerSnapshot> sse_decode_list_peer_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  List<PendingFriendRequest> sse_decode_list_pending_friend_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PendingFriendRequest>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pending_friend_request(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RiverComment> sse_decode_list_river_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RiverComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_river_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<RiverHeart> sse_decode_list_river_heart(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RiverHeart>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_river_heart(deserializer));
    }
    return ans_;
  }

  @protected
  List<RiverPost> sse_decode_list_river_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RiverPost>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_river_post(deserializer));
    }
    return ans_;
  }

  @protected
  MediaAttachment sse_decode_media_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_media_kind(deserializer);
    var var_blobHash = sse_decode_String(deserializer);
    var var_byteLen = sse_decode_u_64(deserializer);
    var var_mime = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_waveform = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    return MediaAttachment(
      kind: var_kind,
      blobHash: var_blobHash,
      byteLen: var_byteLen,
      mime: var_mime,
      durationMs: var_durationMs,
      waveform: var_waveform,
      width: var_width,
      height: var_height,
      fileName: var_fileName,
    );
  }

  @protected
  MediaDraftInput sse_decode_media_draft_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_waveform = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return MediaDraftInput(
      path: var_path,
      durationMs: var_durationMs,
      waveform: var_waveform,
    );
  }

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaKind.values[inner];
  }

  @protected
  NodeIdentitySnapshot sse_decode_node_identity_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_relayUrl = sse_decode_opt_String(deserializer);
    var var_localListenAddrs = sse_decode_list_String(deserializer);
    return NodeIdentitySnapshot(
      nodeId: var_nodeId,
      relayUrl: var_relayUrl,
      localListenAddrs: var_localListenAddrs,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerConnectionState sse_decode_peer_connection_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PeerConnectionState.values[inner];
  }

  @protected
  PeerDiscoveryMethod sse_decode_peer_discovery_method(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PeerDiscoveryMethod.values[inner];
  }

  @protected
  PeerSnapshot sse_decode_peer_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_state = sse_decode_peer_connection_state(deserializer);
    var var_discoveredVia = sse_decode_peer_discovery_method(deserializer);
    var var_lastSeenUnixMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_rttMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    return PeerSnapshot(
      nodeId: var_nodeId,
      state: var_state,
      discoveredVia: var_discoveredVia,
      lastSeenUnixMs: var_lastSeenUnixMs,
      rttMs: var_rttMs,
    );
  }

  @protected
  PendingFriendRequest sse_decode_pending_friend_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requesterProfileId = sse_decode_String(deserializer);
    var var_requesterDisplayName = sse_decode_String(deserializer);
    var var_greeting = sse_decode_opt_String(deserializer);
    var var_recordedAt = sse_decode_u_64(deserializer);
    return PendingFriendRequest(
      requesterProfileId: var_requesterProfileId,
      requesterDisplayName: var_requesterDisplayName,
      greeting: var_greeting,
      recordedAt: var_recordedAt,
    );
  }

  @protected
  ReducedPost sse_decode_reduced_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_profileId = sse_decode_String(deserializer);
    var var_postId = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_media = sse_decode_list_media_attachment(deserializer);
    var var_visibility = sse_decode_visibility(deserializer);
    var var_expiresAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_edited = sse_decode_bool(deserializer);
    return ReducedPost(
      profileId: var_profileId,
      postId: var_postId,
      body: var_body,
      media: var_media,
      visibility: var_visibility,
      expiresAt: var_expiresAt,
      createdAt: var_createdAt,
      edited: var_edited,
    );
  }

  @protected
  RelayMode sse_decode_relay_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RelayMode.values[inner];
  }

  @protected
  RiverComment sse_decode_river_comment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_commenterProfileId = sse_decode_String(deserializer);
    var var_commenterDisplayName = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    return RiverComment(
      commenterProfileId: var_commenterProfileId,
      commenterDisplayName: var_commenterDisplayName,
      body: var_body,
      createdAt: var_createdAt,
    );
  }

  @protected
  RiverHeart sse_decode_river_heart(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hearterProfileId = sse_decode_String(deserializer);
    var var_hearterDisplayName = sse_decode_String(deserializer);
    return RiverHeart(
      hearterProfileId: var_hearterProfileId,
      hearterDisplayName: var_hearterDisplayName,
    );
  }

  @protected
  RiverPost sse_decode_river_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authorProfileId = sse_decode_String(deserializer);
    var var_authorDisplayName = sse_decode_String(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_post = sse_decode_reduced_post(deserializer);
    var var_hearts = sse_decode_list_river_heart(deserializer);
    var var_heartedByMe = sse_decode_bool(deserializer);
    var var_comments = sse_decode_list_river_comment(deserializer);
    var var_keptByMe = sse_decode_bool(deserializer);
    return RiverPost(
      authorProfileId: var_authorProfileId,
      authorDisplayName: var_authorDisplayName,
      isSelf: var_isSelf,
      post: var_post,
      hearts: var_hearts,
      heartedByMe: var_heartedByMe,
      comments: var_comments,
      keptByMe: var_keptByMe,
    );
  }

  @protected
  SettingsView sse_decode_settings_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mdnsEnabled = sse_decode_bool(deserializer);
    var var_relayMode = sse_decode_relay_mode(deserializer);
    var var_customRelayUrl = sse_decode_opt_String(deserializer);
    var var_defaultDownloadDir = sse_decode_opt_String(deserializer);
    return SettingsView(
      mdnsEnabled: var_mdnsEnabled,
      relayMode: var_relayMode,
      customRelayUrl: var_customRelayUrl,
      defaultDownloadDir: var_defaultDownloadDir,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_8(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_bio = sse_decode_String(deserializer);
    var var_defaultVisibility = sse_decode_visibility(deserializer);
    var var_defaultLifetimeSecs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_onboarded = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_updatedAt = sse_decode_u_64(deserializer);
    return UserProfile(
      version: var_version,
      profileId: var_profileId,
      displayName: var_displayName,
      bio: var_bio,
      defaultVisibility: var_defaultVisibility,
      defaultLifetimeSecs: var_defaultLifetimeSecs,
      onboarded: var_onboarded,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Visibility sse_decode_visibility(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Visibility.values[inner];
  }

  @protected
  WavSummary sse_decode_wav_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_waveform = sse_decode_list_prim_u_8_strict(deserializer);
    return WavSummary(durationMs: var_durationMs, waveform: var_waveform);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_jyn_event_Sse(
    RustStreamSink<JynEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_jyn_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_diagnostics_snapshot(
    DiagnosticsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_diagnostics_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_user_profile(
    UserProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user_profile(self, serializer);
  }

  @protected
  void sse_encode_connection_history_entry(
    ConnectionHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.atUnixMs, serializer);
    sse_encode_opt_String(self.peerNodeId, serializer);
    sse_encode_String(self.event, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_opt_box_autoadd_u_64(self.establishMs, serializer);
  }

  @protected
  void sse_encode_diagnostic_error_entry(
    DiagnosticErrorEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.atUnixMs, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_diagnostics_snapshot(
    DiagnosticsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.capturedAtUnixMs, serializer);
    sse_encode_node_identity_snapshot(self.nodeIdentity, serializer);
    sse_encode_list_peer_snapshot(self.peers, serializer);
    sse_encode_list_connection_history_entry(
      self.connectionHistory,
      serializer,
    );
    sse_encode_list_diagnostic_error_entry(self.errorLog, serializer);
    sse_encode_list_gossip_topic_snapshot(self.gossipTopics, serializer);
  }

  @protected
  void sse_encode_friend_entry(FriendEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.profileId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.followsMeBack, serializer);
  }

  @protected
  void sse_encode_ghost_card(GhostCard self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.carrierDisplayName, serializer);
    sse_encode_String(self.authorProfileId, serializer);
  }

  @protected
  void sse_encode_gossip_topic_snapshot(
    GossipTopicSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.topicId, serializer);
    sse_encode_usize(self.peerCount, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_jyn_event(JynEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case JynEvent_River(posts: final posts, ghosts: final ghosts):
        sse_encode_i_32(0, serializer);
        sse_encode_list_river_post(posts, serializer);
        sse_encode_list_ghost_card(ghosts, serializer);
      case JynEvent_Profile(profile: final profile):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_user_profile(profile, serializer);
      case JynEvent_Friends(friends: final friends, pending: final pending):
        sse_encode_i_32(2, serializer);
        sse_encode_list_friend_entry(friends, serializer);
        sse_encode_list_pending_friend_request(pending, serializer);
      case JynEvent_Diagnostics(snapshot: final snapshot):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_diagnostics_snapshot(snapshot, serializer);
      case JynEvent_MediaReady(blobHash: final blobHash, path: final path):
        sse_encode_i_32(4, serializer);
        sse_encode_String(blobHash, serializer);
        sse_encode_String(path, serializer);
      case JynEvent_MediaFailed(
        blobHash: final blobHash,
        errorMessage: final errorMessage,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(blobHash, serializer);
        sse_encode_String(errorMessage, serializer);
      case JynEvent_Error(context: final context, message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(context, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_connection_history_entry(
    List<ConnectionHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connection_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diagnostic_error_entry(
    List<DiagnosticErrorEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diagnostic_error_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_friend_entry(
    List<FriendEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_friend_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ghost_card(
    List<GhostCard> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ghost_card(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gossip_topic_snapshot(
    List<GossipTopicSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gossip_topic_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_attachment(
    List<MediaAttachment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_draft_input(
    List<MediaDraftInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_draft_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_snapshot(
    List<PeerSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pending_friend_request(
    List<PendingFriendRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pending_friend_request(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_river_comment(
    List<RiverComment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_river_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_river_heart(
    List<RiverHeart> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_river_heart(item, serializer);
    }
  }

  @protected
  void sse_encode_list_river_post(
    List<RiverPost> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_river_post(item, serializer);
    }
  }

  @protected
  void sse_encode_media_attachment(
    MediaAttachment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_kind(self.kind, serializer);
    sse_encode_String(self.blobHash, serializer);
    sse_encode_u_64(self.byteLen, serializer);
    sse_encode_String(self.mime, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.waveform, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_String(self.fileName, serializer);
  }

  @protected
  void sse_encode_media_draft_input(
    MediaDraftInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.waveform, serializer);
  }

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_node_identity_snapshot(
    NodeIdentitySnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_opt_String(self.relayUrl, serializer);
    sse_encode_list_String(self.localListenAddrs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_connection_state(
    PeerConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_peer_discovery_method(
    PeerDiscoveryMethod self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_peer_snapshot(PeerSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_peer_connection_state(self.state, serializer);
    sse_encode_peer_discovery_method(self.discoveredVia, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lastSeenUnixMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.rttMs, serializer);
  }

  @protected
  void sse_encode_pending_friend_request(
    PendingFriendRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.requesterProfileId, serializer);
    sse_encode_String(self.requesterDisplayName, serializer);
    sse_encode_opt_String(self.greeting, serializer);
    sse_encode_u_64(self.recordedAt, serializer);
  }

  @protected
  void sse_encode_reduced_post(ReducedPost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.profileId, serializer);
    sse_encode_String(self.postId, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_list_media_attachment(self.media, serializer);
    sse_encode_visibility(self.visibility, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expiresAt, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_bool(self.edited, serializer);
  }

  @protected
  void sse_encode_relay_mode(RelayMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_river_comment(RiverComment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.commenterProfileId, serializer);
    sse_encode_String(self.commenterDisplayName, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_u_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_river_heart(RiverHeart self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hearterProfileId, serializer);
    sse_encode_String(self.hearterDisplayName, serializer);
  }

  @protected
  void sse_encode_river_post(RiverPost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.authorProfileId, serializer);
    sse_encode_String(self.authorDisplayName, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_reduced_post(self.post, serializer);
    sse_encode_list_river_heart(self.hearts, serializer);
    sse_encode_bool(self.heartedByMe, serializer);
    sse_encode_list_river_comment(self.comments, serializer);
    sse_encode_bool(self.keptByMe, serializer);
  }

  @protected
  void sse_encode_settings_view(SettingsView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.mdnsEnabled, serializer);
    sse_encode_relay_mode(self.relayMode, serializer);
    sse_encode_opt_String(self.customRelayUrl, serializer);
    sse_encode_opt_String(self.defaultDownloadDir, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.version, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.bio, serializer);
    sse_encode_visibility(self.defaultVisibility, serializer);
    sse_encode_opt_box_autoadd_u_64(self.defaultLifetimeSecs, serializer);
    sse_encode_bool(self.onboarded, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_u_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_visibility(Visibility self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_wav_summary(WavSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_list_prim_u_8_strict(self.waveform, serializer);
  }
}
