// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/commands.dart';
import 'api/lifecycle.dart';
import 'api/media.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'diagnostics.dart';
import 'domain.dart';
import 'frb_generated.dart';
import 'groups.dart';
import 'groups/reduce.dart';
import 'groups/service.dart';
import 'media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'profile.dart';
import 'runtime.dart';
import 'settings.dart';
import 'state.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  RustStreamSink<JynEvent> dco_decode_StreamSink_jyn_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiagnosticsSnapshot dco_decode_box_autoadd_diagnostics_snapshot(dynamic raw);

  @protected
  GroupDiscoverability dco_decode_box_autoadd_group_discoverability(
    dynamic raw,
  );

  @protected
  GroupJoinMode dco_decode_box_autoadd_group_join_mode(dynamic raw);

  @protected
  GroupView dco_decode_box_autoadd_group_view(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile dco_decode_box_autoadd_user_profile(dynamic raw);

  @protected
  ConnectionHistoryEntry dco_decode_connection_history_entry(dynamic raw);

  @protected
  DiagnosticErrorEntry dco_decode_diagnostic_error_entry(dynamic raw);

  @protected
  DiagnosticsSnapshot dco_decode_diagnostics_snapshot(dynamic raw);

  @protected
  FriendEntry dco_decode_friend_entry(dynamic raw);

  @protected
  GhostCard dco_decode_ghost_card(dynamic raw);

  @protected
  GossipTopicSnapshot dco_decode_gossip_topic_snapshot(dynamic raw);

  @protected
  GroupComment dco_decode_group_comment(dynamic raw);

  @protected
  GroupContentMode dco_decode_group_content_mode(dynamic raw);

  @protected
  GroupDigestDoor dco_decode_group_digest_door(dynamic raw);

  @protected
  GroupDiscoverability dco_decode_group_discoverability(dynamic raw);

  @protected
  GroupDiscoveryCard dco_decode_group_discovery_card(dynamic raw);

  @protected
  GroupHeart dco_decode_group_heart(dynamic raw);

  @protected
  GroupJoinMode dco_decode_group_join_mode(dynamic raw);

  @protected
  GroupJoinRequest dco_decode_group_join_request(dynamic raw);

  @protected
  GroupMemberEntry dco_decode_group_member_entry(dynamic raw);

  @protected
  GroupRole dco_decode_group_role(dynamic raw);

  @protected
  GroupSuggestion dco_decode_group_suggestion(dynamic raw);

  @protected
  GroupView dco_decode_group_view(dynamic raw);

  @protected
  GroupViewerStatus dco_decode_group_viewer_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JynEvent dco_decode_jyn_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConnectionHistoryEntry> dco_decode_list_connection_history_entry(
    dynamic raw,
  );

  @protected
  List<DiagnosticErrorEntry> dco_decode_list_diagnostic_error_entry(
    dynamic raw,
  );

  @protected
  List<FriendEntry> dco_decode_list_friend_entry(dynamic raw);

  @protected
  List<GhostCard> dco_decode_list_ghost_card(dynamic raw);

  @protected
  List<GossipTopicSnapshot> dco_decode_list_gossip_topic_snapshot(dynamic raw);

  @protected
  List<GroupComment> dco_decode_list_group_comment(dynamic raw);

  @protected
  List<GroupDigestDoor> dco_decode_list_group_digest_door(dynamic raw);

  @protected
  List<GroupDiscoveryCard> dco_decode_list_group_discovery_card(dynamic raw);

  @protected
  List<GroupHeart> dco_decode_list_group_heart(dynamic raw);

  @protected
  List<GroupJoinRequest> dco_decode_list_group_join_request(dynamic raw);

  @protected
  List<GroupMemberEntry> dco_decode_list_group_member_entry(dynamic raw);

  @protected
  List<GroupRole> dco_decode_list_group_role(dynamic raw);

  @protected
  List<GroupSuggestion> dco_decode_list_group_suggestion(dynamic raw);

  @protected
  List<MediaAttachment> dco_decode_list_media_attachment(dynamic raw);

  @protected
  List<MediaDraftInput> dco_decode_list_media_draft_input(dynamic raw);

  @protected
  List<PeerSnapshot> dco_decode_list_peer_snapshot(dynamic raw);

  @protected
  List<PendingFriendRequest> dco_decode_list_pending_friend_request(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReducedPost> dco_decode_list_reduced_post(dynamic raw);

  @protected
  List<RiverComment> dco_decode_list_river_comment(dynamic raw);

  @protected
  List<RiverHeart> dco_decode_list_river_heart(dynamic raw);

  @protected
  List<RiverPost> dco_decode_list_river_post(dynamic raw);

  @protected
  MediaAttachment dco_decode_media_attachment(dynamic raw);

  @protected
  MediaBackupMode dco_decode_media_backup_mode(dynamic raw);

  @protected
  MediaDraftInput dco_decode_media_draft_input(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  NodeIdentitySnapshot dco_decode_node_identity_snapshot(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GroupDiscoverability? dco_decode_opt_box_autoadd_group_discoverability(
    dynamic raw,
  );

  @protected
  GroupJoinMode? dco_decode_opt_box_autoadd_group_join_mode(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PeerConnectionState dco_decode_peer_connection_state(dynamic raw);

  @protected
  PeerDiscoveryMethod dco_decode_peer_discovery_method(dynamic raw);

  @protected
  PeerSnapshot dco_decode_peer_snapshot(dynamic raw);

  @protected
  PendingFriendRequest dco_decode_pending_friend_request(dynamic raw);

  @protected
  ReducedPost dco_decode_reduced_post(dynamic raw);

  @protected
  RelayMode dco_decode_relay_mode(dynamic raw);

  @protected
  RiverComment dco_decode_river_comment(dynamic raw);

  @protected
  RiverHeart dco_decode_river_heart(dynamic raw);

  @protected
  RiverPost dco_decode_river_post(dynamic raw);

  @protected
  SettingsView dco_decode_settings_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Visibility dco_decode_visibility(dynamic raw);

  @protected
  WavSummary dco_decode_wav_summary(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  RustStreamSink<JynEvent> sse_decode_StreamSink_jyn_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiagnosticsSnapshot sse_decode_box_autoadd_diagnostics_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GroupDiscoverability sse_decode_box_autoadd_group_discoverability(
    SseDeserializer deserializer,
  );

  @protected
  GroupJoinMode sse_decode_box_autoadd_group_join_mode(
    SseDeserializer deserializer,
  );

  @protected
  GroupView sse_decode_box_autoadd_group_view(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_box_autoadd_user_profile(SseDeserializer deserializer);

  @protected
  ConnectionHistoryEntry sse_decode_connection_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosticErrorEntry sse_decode_diagnostic_error_entry(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosticsSnapshot sse_decode_diagnostics_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  FriendEntry sse_decode_friend_entry(SseDeserializer deserializer);

  @protected
  GhostCard sse_decode_ghost_card(SseDeserializer deserializer);

  @protected
  GossipTopicSnapshot sse_decode_gossip_topic_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GroupComment sse_decode_group_comment(SseDeserializer deserializer);

  @protected
  GroupContentMode sse_decode_group_content_mode(SseDeserializer deserializer);

  @protected
  GroupDigestDoor sse_decode_group_digest_door(SseDeserializer deserializer);

  @protected
  GroupDiscoverability sse_decode_group_discoverability(
    SseDeserializer deserializer,
  );

  @protected
  GroupDiscoveryCard sse_decode_group_discovery_card(
    SseDeserializer deserializer,
  );

  @protected
  GroupHeart sse_decode_group_heart(SseDeserializer deserializer);

  @protected
  GroupJoinMode sse_decode_group_join_mode(SseDeserializer deserializer);

  @protected
  GroupJoinRequest sse_decode_group_join_request(SseDeserializer deserializer);

  @protected
  GroupMemberEntry sse_decode_group_member_entry(SseDeserializer deserializer);

  @protected
  GroupRole sse_decode_group_role(SseDeserializer deserializer);

  @protected
  GroupSuggestion sse_decode_group_suggestion(SseDeserializer deserializer);

  @protected
  GroupView sse_decode_group_view(SseDeserializer deserializer);

  @protected
  GroupViewerStatus sse_decode_group_viewer_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JynEvent sse_decode_jyn_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConnectionHistoryEntry> sse_decode_list_connection_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<DiagnosticErrorEntry> sse_decode_list_diagnostic_error_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FriendEntry> sse_decode_list_friend_entry(SseDeserializer deserializer);

  @protected
  List<GhostCard> sse_decode_list_ghost_card(SseDeserializer deserializer);

  @protected
  List<GossipTopicSnapshot> sse_decode_list_gossip_topic_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupComment> sse_decode_list_group_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupDigestDoor> sse_decode_list_group_digest_door(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupDiscoveryCard> sse_decode_list_group_discovery_card(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupHeart> sse_decode_list_group_heart(SseDeserializer deserializer);

  @protected
  List<GroupJoinRequest> sse_decode_list_group_join_request(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupMemberEntry> sse_decode_list_group_member_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupRole> sse_decode_list_group_role(SseDeserializer deserializer);

  @protected
  List<GroupSuggestion> sse_decode_list_group_suggestion(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaAttachment> sse_decode_list_media_attachment(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaDraftInput> sse_decode_list_media_draft_input(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerSnapshot> sse_decode_list_peer_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingFriendRequest> sse_decode_list_pending_friend_request(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReducedPost> sse_decode_list_reduced_post(SseDeserializer deserializer);

  @protected
  List<RiverComment> sse_decode_list_river_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<RiverHeart> sse_decode_list_river_heart(SseDeserializer deserializer);

  @protected
  List<RiverPost> sse_decode_list_river_post(SseDeserializer deserializer);

  @protected
  MediaAttachment sse_decode_media_attachment(SseDeserializer deserializer);

  @protected
  MediaBackupMode sse_decode_media_backup_mode(SseDeserializer deserializer);

  @protected
  MediaDraftInput sse_decode_media_draft_input(SseDeserializer deserializer);

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  NodeIdentitySnapshot sse_decode_node_identity_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GroupDiscoverability? sse_decode_opt_box_autoadd_group_discoverability(
    SseDeserializer deserializer,
  );

  @protected
  GroupJoinMode? sse_decode_opt_box_autoadd_group_join_mode(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PeerConnectionState sse_decode_peer_connection_state(
    SseDeserializer deserializer,
  );

  @protected
  PeerDiscoveryMethod sse_decode_peer_discovery_method(
    SseDeserializer deserializer,
  );

  @protected
  PeerSnapshot sse_decode_peer_snapshot(SseDeserializer deserializer);

  @protected
  PendingFriendRequest sse_decode_pending_friend_request(
    SseDeserializer deserializer,
  );

  @protected
  ReducedPost sse_decode_reduced_post(SseDeserializer deserializer);

  @protected
  RelayMode sse_decode_relay_mode(SseDeserializer deserializer);

  @protected
  RiverComment sse_decode_river_comment(SseDeserializer deserializer);

  @protected
  RiverHeart sse_decode_river_heart(SseDeserializer deserializer);

  @protected
  RiverPost sse_decode_river_post(SseDeserializer deserializer);

  @protected
  SettingsView sse_decode_settings_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Visibility sse_decode_visibility(SseDeserializer deserializer);

  @protected
  WavSummary sse_decode_wav_summary(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_jyn_event_Sse(
    RustStreamSink<JynEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_diagnostics_snapshot(
    DiagnosticsSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_discoverability(
    GroupDiscoverability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_join_mode(
    GroupJoinMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_view(
    GroupView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_profile(
    UserProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_history_entry(
    ConnectionHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostic_error_entry(
    DiagnosticErrorEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostics_snapshot(
    DiagnosticsSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_entry(FriendEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ghost_card(GhostCard self, SseSerializer serializer);

  @protected
  void sse_encode_gossip_topic_snapshot(
    GossipTopicSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_comment(GroupComment self, SseSerializer serializer);

  @protected
  void sse_encode_group_content_mode(
    GroupContentMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_digest_door(
    GroupDigestDoor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_discoverability(
    GroupDiscoverability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_discovery_card(
    GroupDiscoveryCard self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_heart(GroupHeart self, SseSerializer serializer);

  @protected
  void sse_encode_group_join_mode(GroupJoinMode self, SseSerializer serializer);

  @protected
  void sse_encode_group_join_request(
    GroupJoinRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_member_entry(
    GroupMemberEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_role(GroupRole self, SseSerializer serializer);

  @protected
  void sse_encode_group_suggestion(
    GroupSuggestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_view(GroupView self, SseSerializer serializer);

  @protected
  void sse_encode_group_viewer_status(
    GroupViewerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_jyn_event(JynEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_connection_history_entry(
    List<ConnectionHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diagnostic_error_entry(
    List<DiagnosticErrorEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_entry(
    List<FriendEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ghost_card(
    List<GhostCard> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gossip_topic_snapshot(
    List<GossipTopicSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_comment(
    List<GroupComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_digest_door(
    List<GroupDigestDoor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_discovery_card(
    List<GroupDiscoveryCard> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_heart(
    List<GroupHeart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_join_request(
    List<GroupJoinRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member_entry(
    List<GroupMemberEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_role(
    List<GroupRole> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_suggestion(
    List<GroupSuggestion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_attachment(
    List<MediaAttachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_draft_input(
    List<MediaDraftInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_snapshot(
    List<PeerSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_friend_request(
    List<PendingFriendRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reduced_post(
    List<ReducedPost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_river_comment(
    List<RiverComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_river_heart(
    List<RiverHeart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_river_post(
    List<RiverPost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_attachment(
    MediaAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_backup_mode(
    MediaBackupMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_draft_input(
    MediaDraftInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_node_identity_snapshot(
    NodeIdentitySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_group_discoverability(
    GroupDiscoverability? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_group_join_mode(
    GroupJoinMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_connection_state(
    PeerConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_discovery_method(
    PeerDiscoveryMethod self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_snapshot(PeerSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_pending_friend_request(
    PendingFriendRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reduced_post(ReducedPost self, SseSerializer serializer);

  @protected
  void sse_encode_relay_mode(RelayMode self, SseSerializer serializer);

  @protected
  void sse_encode_river_comment(RiverComment self, SseSerializer serializer);

  @protected
  void sse_encode_river_heart(RiverHeart self, SseSerializer serializer);

  @protected
  void sse_encode_river_post(RiverPost self, SseSerializer serializer);

  @protected
  void sse_encode_settings_view(SettingsView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_visibility(Visibility self, SseSerializer serializer);

  @protected
  void sse_encode_wav_summary(WavSummary self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
