// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The fixed visibility of a Group's posts (ADR-0002). Immutable after
/// creation (ADR-0006).
enum GroupContentMode {
  /// Plaintext, readable by anyone.
  public,

  /// Encrypted to the members; unreadable to non-members and passive peers.
  membersOnly,
}

/// Whether members may advertise their membership to their friends
/// (ADR-0008). Owner-mutable; default listed.
enum GroupDiscoverability { listed, unlisted }

/// How a person becomes a Member (ADR-0002, ADR-0005). Owner-mutable.
enum GroupJoinMode {
  /// The Owner's node auto-accepts join requests.
  open,

  /// The Owner approves each request manually.
  request,
}

/// A role held by a Member. Membership entries carry a *set* of roles
/// (ADR-0001, ADR-0014); phase one populates only these two.
enum GroupRole {
  /// Governs the group: the sole `Manage` holder in phase one.
  owner,

  /// Posts and reads: `Write`.
  member,
}
