// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Duration and waveform peaks for a recorded voice note.
class WavSummary {
  final BigInt durationMs;
  final Uint8List waveform;

  const WavSummary({required this.durationMs, required this.waveform});

  @override
  int get hashCode => durationMs.hashCode ^ waveform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WavSummary &&
          runtimeType == other.runtimeType &&
          durationMs == other.durationMs &&
          waveform == other.waveform;
}
