// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UserProfile {
  final int version;

  /// Hex-encoded public key; the identity itself.
  final String profileId;
  final String displayName;
  final String bio;
  final Visibility defaultVisibility;
  final BigInt? defaultLifetimeSecs;

  /// Whether the owner has been through the first-hour flow.
  final bool onboarded;
  final BigInt createdAt;
  final BigInt updatedAt;

  const UserProfile({
    required this.version,
    required this.profileId,
    required this.displayName,
    required this.bio,
    required this.defaultVisibility,
    this.defaultLifetimeSecs,
    required this.onboarded,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      profileId.hashCode ^
      displayName.hashCode ^
      bio.hashCode ^
      defaultVisibility.hashCode ^
      defaultLifetimeSecs.hashCode ^
      onboarded.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          profileId == other.profileId &&
          displayName == other.displayName &&
          bio == other.bio &&
          defaultVisibility == other.defaultVisibility &&
          defaultLifetimeSecs == other.defaultLifetimeSecs &&
          onboarded == other.onboarded &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
