// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'diagnostics.dart';
import 'domain.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'profile.dart';
import 'state.dart';
part 'runtime.freezed.dart';

class FriendEntry {
  final String profileId;
  final String displayName;

  /// Whether the friendship is mutual yet.
  final bool followsMeBack;

  const FriendEntry({
    required this.profileId,
    required this.displayName,
    required this.followsMeBack,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^ displayName.hashCode ^ followsMeBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendEntry &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          displayName == other.displayName &&
          followsMeBack == other.followsMeBack;
}

@freezed
sealed class JynEvent with _$JynEvent {
  const JynEvent._();

  /// The materialized feed: alive posts newest-first, plus discovery
  /// ghosts (doors to authors we don't follow yet).
  const factory JynEvent.river({
    required List<RiverPost> posts,
    required List<GhostCard> ghosts,
  }) = JynEvent_River;

  /// The local profile (onboarding state, composer defaults, name).
  const factory JynEvent.profile({required UserProfile profile}) =
      JynEvent_Profile;

  /// Friends and pending incoming requests.
  const factory JynEvent.friends({
    required List<FriendEntry> friends,
    required List<PendingFriendRequest> pending,
  }) = JynEvent_Friends;
  const factory JynEvent.diagnostics({required DiagnosticsSnapshot snapshot}) =
      JynEvent_Diagnostics;

  /// A fetched (or freshly cast) attachment blob is available locally.
  const factory JynEvent.mediaReady({
    required String blobHash,
    required String path,
  }) = JynEvent_MediaReady;
  const factory JynEvent.mediaFailed({
    required String blobHash,
    required String errorMessage,
  }) = JynEvent_MediaFailed;

  /// A background failure worth showing (user-action failures throw at
  /// their Dart call sites instead).
  const factory JynEvent.error({
    required String context,
    required String message,
  }) = JynEvent_Error;
}
