// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'diagnostics.dart';
import 'domain.dart';
import 'frb_generated.dart';
import 'groups.dart';
import 'groups/reduce.dart';
import 'groups/service.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'profile.dart';
import 'state.dart';
part 'runtime.freezed.dart';

class FriendEntry {
  final String profileId;
  final String displayName;

  /// Whether the friendship is mutual yet.
  final bool followsMeBack;

  const FriendEntry({
    required this.profileId,
    required this.displayName,
    required this.followsMeBack,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^ displayName.hashCode ^ followsMeBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendEntry &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          displayName == other.displayName &&
          followsMeBack == other.followsMeBack;
}

/// A single river entry per member-group with new activity, opening the
/// group place — group posts never interleave individually (ADR-0010).
class GroupDigestDoor {
  final String groupId;
  final String name;

  /// Sorts the door into the reverse-chron river.
  final int latestActivityAt;

  const GroupDigestDoor({
    required this.groupId,
    required this.name,
    required this.latestActivityAt,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ name.hashCode ^ latestActivityAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDigestDoor &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          name == other.name &&
          latestActivityAt == other.latestActivityAt;
}

@freezed
sealed class JynEvent with _$JynEvent {
  const JynEvent._();

  /// The materialized feed: alive posts newest-first, discovery ghosts
  /// (doors to authors we don't follow yet), one digest door per
  /// member-group with new activity (ADR-0010), and friends' heart-driven
  /// group discovery cards (ADR-0009).
  const factory JynEvent.river({
    required List<RiverPost> posts,
    required List<GhostCard> ghosts,
    required List<GroupDigestDoor> doors,
    required List<GroupDiscoveryCard> groupCards,
  }) = JynEvent_River;

  /// One group's state changed, as this viewer may see it. Dart folds
  /// these into the Groups hub and the group place screens.
  const factory JynEvent.group({required GroupView view}) = JynEvent_Group;

  /// The hub's friend-based suggestions (full snapshot, ADR-0012).
  const factory JynEvent.groupSuggestions({
    required List<GroupSuggestion> suggestions,
  }) = JynEvent_GroupSuggestions;

  /// The local profile (onboarding state, composer defaults, name).
  const factory JynEvent.profile({required UserProfile profile}) =
      JynEvent_Profile;

  /// Friends and pending incoming requests.
  const factory JynEvent.friends({
    required List<FriendEntry> friends,
    required List<PendingFriendRequest> pending,
  }) = JynEvent_Friends;
  const factory JynEvent.diagnostics({required DiagnosticsSnapshot snapshot}) =
      JynEvent_Diagnostics;

  /// A fetched (or freshly cast) attachment blob is available locally.
  const factory JynEvent.mediaReady({
    required String blobHash,
    required String path,
  }) = JynEvent_MediaReady;
  const factory JynEvent.mediaFailed({
    required String blobHash,
    required String errorMessage,
  }) = JynEvent_MediaFailed;

  /// A background failure worth showing (user-action failures throw at
  /// their Dart call sites instead).
  const factory JynEvent.error({
    required String context,
    required String message,
  }) = JynEvent_Error;
}
