// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A greyed-out discovery teaser: a friend's heart points at a post by
/// someone who isn't a friend yet. The content itself is not shown — we
/// don't sync the author — only the door.
class GhostCard {
  final String carrierDisplayName;
  final String authorProfileId;

  const GhostCard({
    required this.carrierDisplayName,
    required this.authorProfileId,
  });

  @override
  int get hashCode => carrierDisplayName.hashCode ^ authorProfileId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GhostCard &&
          runtimeType == other.runtimeType &&
          carrierDisplayName == other.carrierDisplayName &&
          authorProfileId == other.authorProfileId;
}

/// A named discovery card from a friend's heart on a **public + listed**
/// group post: "♥ Bob, in *Group X*" — a pointer into the group place, the
/// post is not copied or moved (ADR-0009).
class GroupDiscoveryCard {
  final String carrierProfileId;
  final String carrierDisplayName;
  final String groupId;
  final String groupName;

  const GroupDiscoveryCard({
    required this.carrierProfileId,
    required this.carrierDisplayName,
    required this.groupId,
    required this.groupName,
  });

  @override
  int get hashCode =>
      carrierProfileId.hashCode ^
      carrierDisplayName.hashCode ^
      groupId.hashCode ^
      groupName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDiscoveryCard &&
          runtimeType == other.runtimeType &&
          carrierProfileId == other.carrierProfileId &&
          carrierDisplayName == other.carrierDisplayName &&
          groupId == other.groupId &&
          groupName == other.groupName;
}

/// A comment under a river post, joined from the commenter's stream.
class RiverComment {
  final String commenterProfileId;
  final String commenterDisplayName;
  final String body;
  final int createdAt;

  const RiverComment({
    required this.commenterProfileId,
    required this.commenterDisplayName,
    required this.body,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      commenterProfileId.hashCode ^
      commenterDisplayName.hashCode ^
      body.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RiverComment &&
          runtimeType == other.runtimeType &&
          commenterProfileId == other.commenterProfileId &&
          commenterDisplayName == other.commenterDisplayName &&
          body == other.body &&
          createdAt == other.createdAt;
}

/// A named heart on a river post.
class RiverHeart {
  final String hearterProfileId;
  final String hearterDisplayName;

  const RiverHeart({
    required this.hearterProfileId,
    required this.hearterDisplayName,
  });

  @override
  int get hashCode => hearterProfileId.hashCode ^ hearterDisplayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RiverHeart &&
          runtimeType == other.runtimeType &&
          hearterProfileId == other.hearterProfileId &&
          hearterDisplayName == other.hearterDisplayName;
}

/// One post as the river renders it.
class RiverPost {
  final String authorProfileId;
  final String authorDisplayName;
  final bool isSelf;
  final ReducedPost post;

  /// Named hearts from everyone whose stream we see (never a bare count).
  final List<RiverHeart> hearts;
  final bool heartedByMe;
  final List<RiverComment> comments;
  final bool keptByMe;

  const RiverPost({
    required this.authorProfileId,
    required this.authorDisplayName,
    required this.isSelf,
    required this.post,
    required this.hearts,
    required this.heartedByMe,
    required this.comments,
    required this.keptByMe,
  });

  @override
  int get hashCode =>
      authorProfileId.hashCode ^
      authorDisplayName.hashCode ^
      isSelf.hashCode ^
      post.hashCode ^
      hearts.hashCode ^
      heartedByMe.hashCode ^
      comments.hashCode ^
      keptByMe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RiverPost &&
          runtimeType == other.runtimeType &&
          authorProfileId == other.authorProfileId &&
          authorDisplayName == other.authorDisplayName &&
          isSelf == other.isSelf &&
          post == other.post &&
          hearts == other.hearts &&
          heartedByMe == other.heartedByMe &&
          comments == other.comments &&
          keptByMe == other.keptByMe;
}
