//! The Bevy-rendered water underlay: deep-water background, animated current
//! spine, and per-card waterline bands, composited beneath the transparent
//! egui layer. See `docs/superpowers/specs/2026-07-04-screen-design-foundations.md`
//! and the "Current & Still" design handoff.

mod card_effects;
// The `allow` covers dead-code lints on validation fns generated by the
// encase `ShaderType` derive inside.
#[allow(dead_code)]
mod water_material;

pub(crate) use card_effects::{setup_render, sync_card_effects};
pub use card_effects::{CardEffect, CardEffects};
pub use water_material::{WaterMaterial, WATER_SHADER_HANDLE};

use bevy::asset::load_internal_asset;
use bevy::prelude::*;
use bevy::sprite::Material2dPlugin;

/// Registers the water underlay: shader, material pipeline, camera and
/// static quads (background + spine), and the per-frame card-effect sync.
pub struct WaterRenderPlugin;

impl Plugin for WaterRenderPlugin {
    fn build(&self, app: &mut App) {
        load_internal_asset!(app, WATER_SHADER_HANDLE, "water.wgsl", Shader::from_wgsl);
        app.add_plugins(Material2dPlugin::<WaterMaterial>::default())
            .init_resource::<CardEffects>()
            .add_systems(Startup, setup_render);
    }
}
