use bevy::asset::weak_handle;
use bevy::prelude::*;
use bevy::render::render_resource::{AsBindGroup, ShaderRef, ShaderType};
use bevy::sprite::{AlphaMode2d, Material2d};

/// Handle under which `water.wgsl` is registered as an internal asset.
pub const WATER_SHADER_HANDLE: Handle<Shader> =
    weak_handle!("6f1b7d61-3f2e-4bd2-9a56-71c66d1a2b6f");

/// Which visual element a [`WaterMaterial`] instance draws.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WaterMode {
    Background = 0,
    Spine = 1,
    Waterline = 2,
    Glow = 3,
}

/// Uniform block shared by all water shader modes.
///
/// `rect` maps the (possibly scroll-clipped) quad's uv into full-element uv
/// space as `(u_min, v_min, u_max, v_max)` so gradients stay anchored while
/// the quad shrinks to its visible intersection.
// The `allow` silences dead-code warnings on per-field validation fns
// generated by the ShaderType derive.
#[derive(Debug, Clone, Copy, ShaderType)]
#[allow(dead_code)]
pub struct WaterSettings {
    pub tint: Vec4,
    pub rect: Vec4,
    pub mode: u32,
    pub element_height_px: f32,
    pub band_frac: f32,
    pub _pad: f32,
}

impl WaterSettings {
    pub fn new(mode: WaterMode) -> Self {
        Self {
            tint: Vec4::ONE,
            rect: Vec4::new(0.0, 0.0, 1.0, 1.0),
            mode: mode as u32,
            element_height_px: 1.0,
            band_frac: 0.0,
            _pad: 0.0,
        }
    }
}

#[derive(Asset, TypePath, AsBindGroup, Debug, Clone)]
pub struct WaterMaterial {
    #[uniform(0)]
    pub settings: WaterSettings,
}

impl WaterMaterial {
    pub fn new(mode: WaterMode) -> Self {
        Self {
            settings: WaterSettings::new(mode),
        }
    }
}

impl Material2d for WaterMaterial {
    fn fragment_shader() -> ShaderRef {
        WATER_SHADER_HANDLE.into()
    }

    fn alpha_mode(&self) -> AlphaMode2d {
        AlphaMode2d::Blend
    }
}
