// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../groups.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A comment on a group post, by any Write-holding member.
class GroupComment {
  final String commentId;
  final String commenterProfileId;
  final String postAuthorProfileId;
  final String postId;
  final String body;
  final int createdAt;

  const GroupComment({
    required this.commentId,
    required this.commenterProfileId,
    required this.postAuthorProfileId,
    required this.postId,
    required this.body,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      commentId.hashCode ^
      commenterProfileId.hashCode ^
      postAuthorProfileId.hashCode ^
      postId.hashCode ^
      body.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupComment &&
          runtimeType == other.runtimeType &&
          commentId == other.commentId &&
          commenterProfileId == other.commenterProfileId &&
          postAuthorProfileId == other.postAuthorProfileId &&
          postId == other.postId &&
          body == other.body &&
          createdAt == other.createdAt;
}

/// An active heart on a group post.
class GroupHeart {
  final String hearterProfileId;
  final String postAuthorProfileId;
  final String postId;
  final int recordedAt;

  const GroupHeart({
    required this.hearterProfileId,
    required this.postAuthorProfileId,
    required this.postId,
    required this.recordedAt,
  });

  @override
  int get hashCode =>
      hearterProfileId.hashCode ^
      postAuthorProfileId.hashCode ^
      postId.hashCode ^
      recordedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupHeart &&
          runtimeType == other.runtimeType &&
          hearterProfileId == other.hearterProfileId &&
          postAuthorProfileId == other.postAuthorProfileId &&
          postId == other.postId &&
          recordedAt == other.recordedAt;
}

/// A join request awaiting the Owner's answer.
class GroupJoinRequest {
  final String requesterProfileId;
  final String requesterDisplayName;
  final String? greeting;
  final int recordedAt;

  const GroupJoinRequest({
    required this.requesterProfileId,
    required this.requesterDisplayName,
    this.greeting,
    required this.recordedAt,
  });

  @override
  int get hashCode =>
      requesterProfileId.hashCode ^
      requesterDisplayName.hashCode ^
      greeting.hashCode ^
      recordedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupJoinRequest &&
          runtimeType == other.runtimeType &&
          requesterProfileId == other.requesterProfileId &&
          requesterDisplayName == other.requesterDisplayName &&
          greeting == other.greeting &&
          recordedAt == other.recordedAt;
}

/// A current member and the set of roles they hold.
class GroupMemberEntry {
  final String profileId;
  final List<GroupRole> roles;

  /// When this membership began (unix seconds).
  final int since;

  const GroupMemberEntry({
    required this.profileId,
    required this.roles,
    required this.since,
  });

  @override
  int get hashCode => profileId.hashCode ^ roles.hashCode ^ since.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberEntry &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          roles == other.roles &&
          since == other.since;
}
