// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import '../groups.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'reduce.dart';

/// A group a friend advertises that the viewer has not joined — the Groups
/// hub's friend-based discovery (ADR-0008, ADR-0012).
class GroupSuggestion {
  final String groupId;
  final String groupName;

  /// The friends advertising membership: provenance for the hub card and
  /// bootstrap peers for reaching the group's topic.
  final List<String> viaFriendProfileIds;

  const GroupSuggestion({
    required this.groupId,
    required this.groupName,
    required this.viaFriendProfileIds,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ groupName.hashCode ^ viaFriendProfileIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupSuggestion &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          viaFriendProfileIds == other.viaFriendProfileIds;
}

/// A group's state as the *local viewer* may see it: the reduction filtered
/// by the visibility rules (roster follows Content mode; pending requests
/// are Owner-only; a members-only group shows non-members no content).
class GroupView {
  final String groupId;
  final String name;
  final GroupContentMode contentMode;
  final GroupJoinMode joinMode;
  final GroupDiscoverability discoverability;
  final int createdAt;
  final String ownerProfileId;
  final GroupViewerStatus viewerStatus;

  /// `None` when the roster is not visible to this viewer.
  final int? memberCount;

  /// Empty when the roster is not visible to this viewer.
  final List<GroupMemberEntry> members;

  /// Owner-only (minus locally denied requests); empty for everyone else.
  final List<GroupJoinRequest> pendingRequests;
  final List<ReducedPost> posts;
  final List<GroupComment> comments;
  final List<GroupHeart> hearts;
  final int latestActivityAt;

  /// Whether the group has activity newer than the viewer's last visit —
  /// what earns it a river digest door (ADR-0010; membership required).
  final bool hasNewActivity;

  const GroupView({
    required this.groupId,
    required this.name,
    required this.contentMode,
    required this.joinMode,
    required this.discoverability,
    required this.createdAt,
    required this.ownerProfileId,
    required this.viewerStatus,
    this.memberCount,
    required this.members,
    required this.pendingRequests,
    required this.posts,
    required this.comments,
    required this.hearts,
    required this.latestActivityAt,
    required this.hasNewActivity,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      name.hashCode ^
      contentMode.hashCode ^
      joinMode.hashCode ^
      discoverability.hashCode ^
      createdAt.hashCode ^
      ownerProfileId.hashCode ^
      viewerStatus.hashCode ^
      memberCount.hashCode ^
      members.hashCode ^
      pendingRequests.hashCode ^
      posts.hashCode ^
      comments.hashCode ^
      hearts.hashCode ^
      latestActivityAt.hashCode ^
      hasNewActivity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupView &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          name == other.name &&
          contentMode == other.contentMode &&
          joinMode == other.joinMode &&
          discoverability == other.discoverability &&
          createdAt == other.createdAt &&
          ownerProfileId == other.ownerProfileId &&
          viewerStatus == other.viewerStatus &&
          memberCount == other.memberCount &&
          members == other.members &&
          pendingRequests == other.pendingRequests &&
          posts == other.posts &&
          comments == other.comments &&
          hearts == other.hearts &&
          latestActivityAt == other.latestActivityAt &&
          hasNewActivity == other.hasNewActivity;
}

/// How the local profile relates to a group, for the UI.
enum GroupViewerStatus {
  /// Holds `Manage` (and posts like any member).
  owner,

  /// Holds `Write`.
  member,

  /// Sent a join request that the Owner has not answered yet.
  pending,
  nonMember,
}
