// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_draft`, `run`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Casts a post. `lifetime_secs` counts from now; `None` is permanent.
Future<void> publishPost({
  required String body,
  required Visibility visibility,
  int? lifetimeSecs,
  required List<MediaDraftInput> media,
}) => RustLib.instance.api.crateApiCommandsPublishPost(
  body: body,
  visibility: visibility,
  lifetimeSecs: lifetimeSecs,
  media: media,
);

Future<void> editPost({required String postId, required String body}) =>
    RustLib.instance.api.crateApiCommandsEditPost(postId: postId, body: body);

Future<void> deletePost({required String postId}) =>
    RustLib.instance.api.crateApiCommandsDeletePost(postId: postId);

/// Promote to permanent (`None`) or let it go again (`Some(unix_secs)`).
Future<void> setPostLifetime({required String postId, int? expiresAt}) =>
    RustLib.instance.api.crateApiCommandsSetPostLifetime(
      postId: postId,
      expiresAt: expiresAt,
    );

Future<void> updateProfile({
  required String displayName,
  required String bio,
  required Visibility defaultVisibility,
  int? defaultLifetimeSecs,
  required bool markOnboarded,
}) => RustLib.instance.api.crateApiCommandsUpdateProfile(
  displayName: displayName,
  bio: bio,
  defaultVisibility: defaultVisibility,
  defaultLifetimeSecs: defaultLifetimeSecs,
  markOnboarded: markOnboarded,
);

/// The share-code ritual: decode a `jyn-` friend code, reach out, and place
/// a friendship request on the target's topic.
Future<void> requestFriendship({
  required String friendCode,
  String? greeting,
}) => RustLib.instance.api.crateApiCommandsRequestFriendship(
  friendCode: friendCode,
  greeting: greeting,
);

/// In-app request to a profile already put in front of us (a ghost card).
Future<void> requestFriendshipById({
  required String profileId,
  String? greeting,
}) => RustLib.instance.api.crateApiCommandsRequestFriendshipById(
  profileId: profileId,
  greeting: greeting,
);

/// Answer a pending request. Accepting follows the requester back and
/// starts syncing their stream.
Future<void> respondFriendship({
  required String requesterProfileId,
  required bool accept,
}) => RustLib.instance.api.crateApiCommandsRespondFriendship(
  requesterProfileId: requesterProfileId,
  accept: accept,
);

Future<void> removeFriend({required String profileId}) =>
    RustLib.instance.api.crateApiCommandsRemoveFriend(profileId: profileId);

/// Toggle a named heart on someone's post.
Future<void> setHeart({
  required String postAuthorProfileId,
  required String postId,
  required bool active,
}) => RustLib.instance.api.crateApiCommandsSetHeart(
  postAuthorProfileId: postAuthorProfileId,
  postId: postId,
  active: active,
);

Future<void> publishComment({
  required String postAuthorProfileId,
  required String postId,
  required String body,
}) => RustLib.instance.api.crateApiCommandsPublishComment(
  postAuthorProfileId: postAuthorProfileId,
  postId: postId,
  body: body,
);

/// Keep a private copy of a post — a lease that dies with the post's
/// lifetime or the author's delete.
Future<void> keepPost({
  required String postAuthorProfileId,
  required String postId,
}) => RustLib.instance.api.crateApiCommandsKeepPost(
  postAuthorProfileId: postAuthorProfileId,
  postId: postId,
);

Future<void> releaseKeep({
  required String postAuthorProfileId,
  required String postId,
}) => RustLib.instance.api.crateApiCommandsReleaseKeep(
  postAuthorProfileId: postAuthorProfileId,
  postId: postId,
);

/// A file staged on the composer. Voice notes carry the duration and
/// waveform from [`crate::api::media::voice_note_summary`]; other files
/// leave them empty. The media kind is derived from the file extension.
class MediaDraftInput {
  final String path;
  final int? durationMs;
  final Uint8List? waveform;

  const MediaDraftInput({required this.path, this.durationMs, this.waveform});

  @override
  int get hashCode => path.hashCode ^ durationMs.hashCode ^ waveform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDraftInput &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          durationMs == other.durationMs &&
          waveform == other.waveform;
}
