// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../diagnostics.dart';
import '../domain.dart';
import '../frb_generated.dart';
import '../groups.dart';
import '../groups/reduce.dart';
import '../groups/service.dart';
import '../profile.dart';
import '../runtime.dart';
import '../state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrbEventSink`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `push`

/// Starts the p2panda node (idempotent). `data_dir_override` beats the
/// `JYN_DATA_DIR` environment variable and the platform default; it only
/// takes effect on the first call of the process.
Future<void> startNode({String? dataDirOverride}) => RustLib.instance.api
    .crateApiLifecycleStartNode(dataDirOverride: dataDirOverride);

/// The runtime's event stream. Events that fired between `start_node` and
/// this call are buffered and replayed, so no startup state is lost.
Stream<JynEvent> events() => RustLib.instance.api.crateApiLifecycleEvents();

/// Desktop notifications only fire while the app is unfocused; Flutter
/// reports focus changes here.
Future<void> setAppFocused({required bool focused}) =>
    RustLib.instance.api.crateApiLifecycleSetAppFocused(focused: focused);

/// The resolved data directory of the running node.
Future<String> nodeDataDir() =>
    RustLib.instance.api.crateApiLifecycleNodeDataDir();

/// The encoded `jyn-` friend code for the local profile. Fails until the
/// profile has loaded (wait for the first Profile event).
Future<String> myFriendCode() =>
    RustLib.instance.api.crateApiLifecycleMyFriendCode();

/// The 24-word recovery phrase for the local identity. It recovers the
/// signing key and, with a backup archive, all encrypted content — treat it
/// like the key it is.
Future<String> recoveryPhrase() =>
    RustLib.instance.api.crateApiLifecycleRecoveryPhrase();

/// Whether this machine has no jyn identity yet (no `node.key` in the data
/// directory). Callable before `start_node`; gates the restore-from-backup
/// offer at first launch.
Future<bool> isFreshInstall() =>
    RustLib.instance.api.crateApiLifecycleIsFreshInstall();

/// Restores a backup archive into the app's data directory using the
/// recovery phrase. Must be called *before* `start_node` (fails once the
/// node runs); the restored identity and content are live after the next
/// `start_node`.
Future<void> restoreBackup({
  required String archivePath,
  required String recoveryPhrase,
}) => RustLib.instance.api.crateApiLifecycleRestoreBackup(
  archivePath: archivePath,
  recoveryPhrase: recoveryPhrase,
);
