// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../media.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Reduces a recorded WAV to the duration + waveform peaks that travel
/// inside the post operation. Call after the recorder finished, pass the
/// result into the matching `MediaDraftInput`.
Future<WavSummary> voiceNoteSummary({required String wavPath}) =>
    RustLib.instance.api.crateApiMediaVoiceNoteSummary(wavPath: wavPath);

/// The local file for a blob if it's already in the media cache.
Future<String?> localMediaPath({required String blobHash}) =>
    RustLib.instance.api.crateApiMediaLocalMediaPath(blobHash: blobHash);

/// Fetches a blob into the media cache unless it's local or already in
/// flight. Completion arrives as a MediaReady / MediaFailed event.
Future<void> requestMedia({required String blobHash}) =>
    RustLib.instance.api.crateApiMediaRequestMedia(blobHash: blobHash);
